services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql_password"
      MYSQL_DATABASE: "chess"
      MYSQL_USER: "chess_user"
      MYSQL_PASSWORD: "mysql_password"

  app:
    build:
      context: app
      dockerfile: Dockerfile.app
    depends_on: 
      - db
    ports:
      - "8080:80"
