# Use an official MySQL image as a parent image
FROM mysql:8.0

# Set the working directory to /docker-entrypoint-initdb.d
WORKDIR /docker-entrypoint-initdb.d

# Copy the SQL file into the container
COPY init.sql /docker-entrypoint-initdb.d/

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD="mysql_password"
ENV MYSQL_DATABASE="chess"
ENV MYSQL_USER="chess_user"
ENV MYSQL_PASSWORD="mysql_password"
